#!/bin/sh
TEMPJSON=temp.json
JSONFILE=weixin.json

rm $TEMPJSON $JSONFILE
type scrapy >/dev/null 2>&1 || { echo >&2 "scrapy is required. you may use pip to install scrapy first."; exit 1; }
scrapy runspider spider/spider.py -o $TEMPJSON
python -m json.tool $TEMPJSON > $JSONFILE
clear
echo "This is the weixin articles information. Check $JSONFILE for details."
cat $JSONFILE
